services:
  postgres:
    image: postgres:16
    container_name: gathering-postgres
    environment:
      POSTGRES_DB: gathering
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - gathering_pg_data:/var/lib/postgresql/data

volumes:
  gathering_pg_data:
